pivotal-cf/docs-mysql-k8s

install-operator.html.md.erb

This was a late change while we were automating our release process.

helm charts use tag 0.1.0

---

release-notes.html.md.erb

- We don't provide any HA yet in this release.
- "pattern" is not generally capitalized in "Operator pattern".
- No comma in "single-node MySQL database instances" (cumulative adjectives)
- I removed it anyway, but "basic high availability" are also cumulative adjectives and should not have a comma.

0.1.0 release note tweaks

---

create-delete-mysql.html.md.erb
property-reference-tanzumysql.html.md.erb

This PR covers several changes:
- rename `backups` container to `sidecar`
- add new rows to property reference table for new `router` container
- simplify language when creating a TanzuMySQL instance. **This is the start of more changes to come**. I would like to guide readers to create their own files and reference our deployment templates. There are more places in the docs where we incorrectly ask them to use our deployment templates and instead they need to create/edit/manage their own YAML files.
Happy to have a discussion on the third point during the weekly docs sync.

Update TanzuMySQL property reference for router

---

README.md
accessing.html.md.erb
backup-restore.html.md.erb
configure-tls.html.md.erb
create-delete-mysql.html.md.erb
property-reference-backup-restore.html.md.erb
update-instance.html.md.erb

Reference new MySQL deployment template names and introduce pattern of having the reader copy the deployment
template rather than edit it directly.
New names:
- mysql.yaml
- backup.yaml
- restore.yaml
- backuplocation.yaml
- backupschedule.yaml
[#176827702](https://www.pivotaltracker.com/story/show/176827702)
Name the branches to merge this change with or enter "None". **None**

Reference new MySQL deployment template names

---

README.md
accessing.html.md.erb
architecture.html.md.erb
backup-restore.html.md.erb
bind-app.html.md.erb
configure-tls.html.md.erb
create-delete-mysql.html.md.erb
property-reference-backup-restore.html.md.erb
property-reference-mysql.html.md.erb
rotating-credentials.html.md.erb
update-instance.html.md.erb
upgrade-operator.html.md.erb

- mysql.tanzu.vmware.com -> sql.tanzu.vmware.com
- TanzuMySQL -> MySQL
- TanzuMySQLBackup -> MySQLBackup
- TanzuMySQLBackupLocation -> MySQLBackupLocation
- TanzuMySQLBackupSchedule -> MySQLBackupSchedule
- TanzuMySQLRestore -> MySQLRestore
Another small change: for upgrading CRDs, I've simplified the instructions to use a directory instead of the exact filename:
```
kubectl apply -f ./tanzu-mysql-operator/crds/
``` 
[#176827765](https://www.pivotaltracker.com/story/show/176827765)
Name the branches to merge this change with or enter "None". **None**

Rename CRDs and group

---

architecture.html.md.erb
backup-restore.html.md.erb
property-reference-backup-restore.html.md.erb

To avoid overloading "cluster" further, we now always reference the
deployed MySQL as an "instance" rather than "cluster" within our config
samples.
Updated docs that reference the Tanzu MySQL configuration to replace
"cluster" with "instance". Remaining usage of the word cluster are now
reference a "Kubernetes cluster" or the default Kubernetes system domain
("svc.cluster.local").
[#176718597](https://www.pivotaltracker.com/story/show/176718597)
This change should only be added to main and will only apply to our next release.

Rename "cluster" to "instance" when reference to a MySQL instance

---

architecture.html.md.erb
backup-restore.html.md.erb
property-reference-backup-restore.html.md.erb

The purpose of this property was to set the "scheme" for the blob
storage endpoint to "http" rather than the implicit "https" when just a
hostname is provided.
This is a rare use case limited to development, so we have removed this
property.  A user using a blob store that does not support TLS should
specify endpoint: "http://my.endpoint/" instead, which we already
demonstrate in the docs.
[#176718452](https://www.pivotaltracker.com/story/show/176718452)
This change should only be added to main and will only apply to our next release.

Remove disableSSL property from docs

---

accessing.html.md.erb

- Some "kubectl exec <podname>" commands did not specify a "-c mysql"
container, instead relying on default ordering. This adds "-c mysql"
where needed.
- Reworded some steps describing pod connection as "Log in to the
Kubernetes namespace", clarified that user is connecting to the
mysql container specifically.
[#177481208](https://www.pivotaltracker.com/story/show/177481208)
Signed-off-by: Kim Bassett <kbassett@pivotal.io>

Specify container on "kubectl exec" commands

---

accessing.html.md.erb
bind-app.html.md.erb

- Consolidated existing app connection instruction onto
bind-app.html page (from prior accessing.html page).
- Added to accessing page reference to bind-app page
discussion.
- (NOTE "helm install wp bitnami/wordpress..." example needs
adjustment to accommodate mysql's secure-transport
requirement. Addressing outside of this commit.)
[#177409309](https://www.pivotaltracker.com/story/show/177409309)

Document non-root application connection

---

release-notes.html.md.erb

New version to be released in v1.0.0.
[#177485551](https://www.pivotaltracker.com/story/show/177485551)
Only affects v1.0.0 release.

percona-xtrabackup has been bumped to 8.0.23-16

---

accessing.html.md.erb
bind-app.html.md.erb

- Some clarification to user connection as root on the
container
- Refer user to app binding instruction for mechanics of
connecting to root for creating user
- Also corrected typo in mysql-instance-0/1 prompt in bind-app
[#175727181](https://www.pivotaltracker.com/story/show/175727181)
Signed-off-by: David Sharp <dsharp@pivotal.io>

Create non-root user for external connection.

---

high-availability.html.md.erb

This was done in https://github.com/pivotal-cf/docs-mysql-k8s/pull/37 but somehow the headless service name came back.
[#177485547](https://www.pivotaltracker.com/story/show/177485547)
Co-authored-by: Kim Bassett <kbassett@vmware.com>

Update headless service to members service

---

high-availability.html.md.erb
property-reference-mysql.html.md.erb
update-instance.html.md.erb

- "spec.resources.sidecar" is now "spec.resources.mysqlSidecar"
- container `mysql-controller` is now `mysql-sidecar`
- continued rename of "router" to "proxy" (when referencing container;
some "router" references remain when referring to process inside
container)
- small editorial tweaks
[#177565260](https://www.pivotaltracker.com/story/show/177565260)
Signed-off-by: Kim Bassett <kbassett@pivotal.io>

Renamed multiple resources

---

install-operator.html.md.erb
upgrade-operator.html.md.erb

In an effort to avoid copyright claims around the use of "MySQL", we are
renaming the operator chart.
[#177568103](https://www.pivotaltracker.com/story/show/177568103)
Co-authored-by: Andrew Garner <garnera@vmware.com>
This only affects the v1.0.0 branch.

rename tanzu-mysql-operator chart to tanzu-sql-for-mysql-operator

---

install-operator.html.md.erb
upgrade-operator.html.md.erb

Mistakenly used the wrong preposition for docs in previous PR. We
decided to use "with" to match the current product name.
[#177568103](https://www.pivotaltracker.com/story/show/177568103)
Co-authored-by: Andrew Garner <garnera@vmware.com>
This only applies to v1.00

Rename tanzu-sql-for-mysql-operator to tanzu-sql-with-mysql-operator

---

architecture.html.md.erb
backup-restore.html.md.erb
property-reference-backup-restore.html.md.erb

- Time columns no longer include microseconds
- Removed "AGE" columns
- Removed "Scheduled" status
- Backups:
- Removed "TIME SCHEDULED"
- Added "SOURCE INSTANCE"
- Restores:
- Added "SOURCE BACKUP" and "TARGET INSTANCE"
- Replace sample name: mysqlrestore-sample -> restore-sample
[#176718745](https://www.pivotaltracker.com/story/show/176718745)
Co-authored-by: Kevin Markwardt <kmarkwardt@vmware.com>
None

Update backup/restore columns

---

configure-tls.html.md.erb

Substantial TLS clarifications
- Pulled SAN topic into standalone bullet point for further
consideration / clarification
- Clarified ClusterIssuer vs Issuer usage WRT namespace
- Delineated `spec.dnsNames`/`spec.ipAddresses` into distinct cases
"within same cluster" vs "outside cluster"
- Replaced example of port forwarded client connection with client
connecting to load-balanced service (presumably closer to a real-
world developer scenario).
- (Small markdown adjusutments WRT numbering spacing etc.)

Clarify tls sans 177564166

---

property-reference-mysql.html.md.erb

I did remove some info from the 'Description' (now 'Information') text of one or two rows, because the table was fairly unwieldy. I attempted to preserve everything possible but simplify.
We do need to restructure the table in some way, because as is, it flows beyond the content area and the right-hand nav obscures part of the table as you scroll.

Restructure the Property Reference table

---

configure-tls.html.md.erb
connecting-apps.html.md.erb
install-operator.html.md.erb
release-notes.html.md.erb

The updated page can be viewed at https://mysql-k8s-install-archive.sc2-04-pcf1-apps.oc.vmware.com/tanzu-mysql-kubernetes/1-1/install-operator.html

“Installing the Operator": add section about install based on downloaded archive

---

property-reference-mysql.html.md.erb

Providing an example values for these property is difficult, because the configuration is quite verbose.   This probably will not render at all nicely in the current table format, but I provided it for now simply because I'm not sure what else we should say for that field.   Perhaps we could link to some other page that describes when a user would set this feature in more detail, but I don't think we have that right now.
This applies only to the docs for 1.2.0 and later.

Provide basic affinity and tolerations property references

---

install-operator.html.md.erb

2 commits:
- 1st commit has a number of clarifications, corrections
- 2nd commit consolidates secret creation instructions and focuses that segment on Operator secret creation (calling out the operator namespace) while also adding emphasis that the user must (re)create secrets in their instance namespaces.

1.3.0 release updates

---

create-delete-mysql.html.md.erb
property-reference-mysql.html.md.erb

These doc changes introduce the new field and the new command. This topic does not deal with the workflow of upgrading instances. 
html version of staging:
https://docs-staging.vmware.com/en/VMware-Tanzu-SQL-with-MySQL-for-Kubernetes/wip_multi_version/tanzu-mysql-k8s/GUID-create-delete-mysql.html

Feature multi version support

---

release-notes.html.md.erb
toc.md

Draft release notes for 1.4.0.
Html version:
https://docs-staging.vmware.com/en/VMware-Tanzu-SQL-with-MySQL-for-Kubernetes/wip_release_notes_1.4.0/tanzu-mysql-k8s/GUID-release-notes.html

Docs - draft 1.4.0 release notes

---

create-delete-mysql.html.md.erb
update-instance.html.md.erb
upgrade-instance.html.md.erb
upgrade-operator.html.md.erb

Updating and upgrading the instances refreshed topics. 
Html render, starting the flow at the bottom of the Upgrade Operator topic:
https://docs-staging.vmware.com/en/VMware-Tanzu-SQL-with-MySQL-for-Kubernetes/wip_instance_upgrade/tanzu-mysql-k8s/GUID-upgrade-operator.html

Feature - multiversion upgrade and update

---

install-operator.html.md.erb

- Added anchor to section "Create Operator Namespace and Secrets",
and reset out-of-date anchors from (non-existent)
#create-service-account to this new tag.
- Articulated during namespace creation:
- default is tanzu-mysql-for-kubernetes-system
- you can change it by replacing it everywhere it appears in
below commands
- Added explicit "--namespace=tanzu-mysql-for-kubernetes-system"
to all Operator-related helm & kubectl commands, so that earlier
guidance on how to change namespace can be applied across the rest
of the page.
- Clarified that the Operator Configuration file is a net new file
which optionally overrides existing values.yaml configuration.
- Updated sample command outputs to correctly reflect namespace
tanzu-mysql-for-kubernetes-system, webhook services, & realistic …

Operator Installation clarifications & corrections:

---

install-operator.html.md.erb
upgrade-operator.html.md.erb

install-operator.html.md.erb:
- Clarify rationale for saving overrides file
upgrade-operator.html.md.erb:
- Clarified assumption that "tanzu-mysql-for-kubernetes-system" is
default-installed namespace, & to substitute user's own as needed
- Moved namespace designation to the end of each command:
before: "helm -n tanzu-mysql-for-kubernetes-system ls"
after:  "helm ls -n tanzu-mysql-for-kubernetes-system"
- Aligned assumptions & formatting with Postgres docs:
- Hard-coded Versions to the current/documented 1.4.0
(removing use of $VERSION-NUMBER-TAG variable in
user-facing instructions).
- Hard-coded registry to indicate standard registry.tanzu.vmware.com
(Removing complex "here is how you might wire in your own registry"
scenario, aligning with our own install and postgres docs)
- fixed …

install/upgrade-operator: helm behavior clarifications

---

install-operator.html.md.erb

Notable changes from Postgres:
- Name of the package: mysql-operator.with.sql.tanzu.vmware.com
- Version: 1.8.0
[#181155437](https://www.pivotaltracker.com/story/show/181155437)
Name the branches to merge this change with or enter "None": 1.5 branch

install-operator: Add installation instructions [1.5]

---

create-delete-mysql.html.md.erb
index.html.md.erb
install-operator.html.md.erb
release-notes.html.md.erb
update-instance.html.md.erb

- I've removed 8.0.25 where needed
- I've added 8.0.29 where needed
- I've setup the basic release notes for 1.6.0. 
For now, I'm going with the assumption that MySQL will release after Postgres and TDS package will be 1.4.0. We can update this as we get closer to the ETA of September 15th.
I've also left the minimum Kubernetes version as 1.19. I don't think this is right but I'll verify and submit a PR for that.

Update MySQL versions for 1.6.0 release

---

install-operator.html.md.erb
upgrade-operator.html.md.erb

- Use consistent namespace for the operator
- Fix indentation of a verbatim block so the following note is legible
- Use markdown link over <a> tag.
- Specify namespace and correct label in `kubectl logs` command
Name the branches to merge this change with or enter "None": 1.6

Corrections from actually running the commands in the install and upgrade docs

---

release-notes.html.md.erb

Name the branches to merge this change with or enter "None". 1.4 branch

release notes: Call out removed operator Chart value defaultInstanceVersion (1.4)

---

troubleshooting.html.md.erb

These sections provide some help in understanding the offline, unreachable, and recovering states in Group Replication.

Add troubleshooting section for Group Replication states

---

create-delete-mysql.html.md.erb
index.html.md.erb
property-reference-mysql.html.md.erb
update-instance.html.md.erb
upgrade-instance.html.md.erb

As part of 1.7.0 Release, we're removing support for mysql 8.0.26 and adding support for mysql 8.0.30

Add support for mysql 8.0.31 and remove support for mysql 8.0.26 [1.7.0 Release]

---

high-availability.html.md.erb
property-reference-mysql.html.md.erb

Add field for HA number of members
Add to Property Reference
Add section to Configuring HA
-should we change the link I've included?
-I think we should link to some further reading, but some of the best resources were blogs, and I thought it was best to only link to MySQL docs or similar. So I'm open to feedback on that choice
-Should I avoid the term 'split-brain' or use it and explain it better?
Authored-by: Ria Mahoney <mpatrice@vmware.com>

Number of HA Members

---

backup-restore.html.md.erb
release-notes.html.md.erb

Change backup storage artifact path to match future binlog path
Start 1.9.0 Release Notes
[#185222215]

[1.9.0] Update backups storage artifact path

---

property-reference-backup-restore.html.md.erb
property-reference-mysql.html.md.erb

WIP 
Add binlog collection resources to the Property Reference for Backup and Restore
-add table entries for `binaryLogCollection.enabled`, and `resources.limits` and `resources.requests`
-close code tags and table row tags that were not closed in prior entries
-fix minor grammar error in the main property reference
Open questions:
-Do we want to add a sample yaml in the backup-restore section? There isn't one now, and I think we should show the full `binaryLogCollection` block that we're adding
-Do we want to link to that in our Release Notes?
-I added a note under the Backup Schedule Property Reference table that links to the main Property Reference description of `memory` and `cpu`. Do we want to duplicate that info **in** or **under** the table for Backup Schedule?
-Do we want to add …

resources for binlog collector deployment

---

update-instance.html.md.erb

We should backport this to the 1.8 and 1.7 branch as well.

Fix outdated volume resize documentation

---

toc.md

Add custom-config page to table of contents
In our last release, we added custom configuration.
We added a page with instructions, and linked to it in the release notes.
But we failed to include Custom Config in the TOC on the left panel.
This commit fixes that
Authored-by: Ria Mahoney <mpatrice@vmware.com>
@dyozie Could we merge this with 1.9.0? And then merge into Main?
It needed to be published with the 1.9 release, and now it needs to be in main with the rest of 1.9
Thank you

Add link to custom config page to the TOC

---

index.html.md.erb

Branch 1.4.
Fixes to broken links per https://bugzilla.eng.vmware.com/show_bug.cgi?id=3294761#c2 in the https://docs.vmware.com/en/VMware-SQL-with-MySQL-for-Kubernetes/1.4/vmware-mysql-k8s/index.html topic.

Fixing links per bug 3294761

---

configure-mysql-server.html.md.erb

The configmap sample was not working because the my.cnf contents were not in the correct format. This commit corrects that format.

Update configmap example to valid mysql cnf format
