pivotal-cf/docs-mysql-k8s

- index.html.md.erb
> Replace Pivotal Beta license with VMware Pre-Release

- release-notes.html.md.erb
added a compatibility table too. maybe @abg can help confirm versions for Percona Server and Xtrabackup?
> release notes for 0.1.0

- configure-tls.html.md.erb
- create-delete-mysql.html.md.erb
- property-reference-tanzumysql.html.md.erb
This is a first pass at describing the new TLS support.
Feedback appreciated!
[#176175842](https://www.pivotaltracker.com/story/show/176175842)
> Document TLS setup and how to verify connection

- accessing.html.md.erb
- create-delete-mysql.html.md.erb
- property-reference-tanzumysql.html.md.erb
First pass at documentation for how to connect to the MySQL server with an external IP.
Feedback appreciated!
[#176230203](https://www.pivotaltracker.com/story/show/176230203)
> Add documentation for connecting with external IP

- accessing.html.md.erb
[#176230203](https://www.pivotaltracker.com/story/show/176230203)
> Correct how we describe MySQL server access

- configure-tls.html.md.erb
[#176175842](https://www.pivotaltracker.com/story/show/176175842)
> Clarify client connection defaults and cert-manager config

- update-instance.html.md.erb
No need to merge to older versions.
> Use `kubectl patch` instead of `kubectl edit`

- install-operator.html.md.erb
- upgrade-operator.html.md.erb
Steps to upgrade from 0.1.0 to latest
> Helm upgrade 176276283

- index.html.md.erb
- install-operator.html.md.erb
- release-notes.html.md.erb
> Update release notes docs for 0.2.0

- install-operator.html.md.erb
Instead of suggesting a user rewrite the `values.yaml` in the helm chart the user
downloaded, suggest that a user create a separate values-override.yaml
file that specifies the configuration they wish to change.
[#176805257](https://www.pivotaltracker.com/story/show/176805257)
> Clarify helm customization instructions

- configure-tls.html.md.erb
[#177033298](https://www.pivotaltracker.com/story/show/177033298)
> Create TLS secret with CA included

- architecture.html.md.erb
- backup-restore.html.md.erb
- create-delete-mysql.html.md.erb
[#177227558](https://www.pivotaltracker.com/story/show/177227558)
> Add prefix `with.` to API Group

- architecture.html.md.erb
- property-reference-backup-restore.html.md.erb
[#176718516](https://www.pivotaltracker.com/story/show/176718516)
Authored-by: David Sharp <dsharp@vmware.com>
None
> Update names of MySQLRestore fields

- architecture.html.md.erb
[#176447098](https://www.pivotaltracker.com/story/show/176447098)
> Rename v1alpha1 to v1 for CRDs

- accessing.html.md.erb
- architecture.html.md.erb
- bind-app.html.md.erb
- configure-tls.html.md.erb
- create-delete-mysql.html.md.erb
- index.html.md.erb
- install-operator.html.md.erb
- property-reference-backup-restore.html.md.erb
- property-reference-mysql.html.md.erb
- release-notes.html.md.erb
- rotating-credentials.html.md.erb
- update-instance.html.md.erb
- upgrade-operator.html.md.erb
- Remove beta warning
- Update EULA
- Remove limitations around upgrades
- Use 1.0.0 where it is needed
- Add draft for 1.0.0 release notes and Known Issues
[#177422605](https://www.pivotaltracker.com/story/show/177422605)
> Prepare docs for 1.0.0 release

- architecture.html.md.erb
- high-availability.html.md.erb
This language is more general and allows us to change the
implementation without concerns on updating the docs to match the name.
[#177485551](https://www.pivotaltracker.com/story/show/177485551)
Co-authored-by: Andrew Garner <garnera@vmware.com>
> Change router pods to proxy pods

- bind-app.html.md.erb
- high-availability.html.md.erb
[#177485547](https://www.pivotaltracker.com/story/show/177485547)
> Rename service from headless to members

- install-operator.html.md.erb
[#177485524](https://www.pivotaltracker.com/story/show/177485524)
This is for v1.0.0 only.
> Rename tanzuMySQLImage to instanceImage

- configure-tls.html.md.erb
Do not use the root password for application connectivity
[#177603468]
Authored-by: Colin Shield <cshield@vmware.com>
Authored-by: Kevin Markwardt <kmarkwardt@vmware.com>
> Added a warning

- architecture.html.md.erb
[#177566881]
Merge this to the main branch
> clarified HA discussion

- create-delete-mysql.html.md.erb
I've also added line breaks to separate the `For example:` a bit more.
[#177566930](https://www.pivotaltracker.com/story/show/177566930)
> Delete PVC by label instead of name

- property-reference-backup-restore.html.md.erb
[#177354510]
Co-authored-by: Kevin Markwardt <kmarkwardt@vmware.com>
None
> Adding comment that the trailing slash is needed

- configure-tls.html.md.erb
Tidied up some text and added a reference to a SAN
[#177564166]
main
> some polish for SAN additions

- release-notes.html.md.erb
[#177751394](https://www.pivotaltracker.com/story/show/177751394)
Name the branches to merge this change with or enter "None". NOne
> Add Known Issues and Limitations for 1.0.0

- monitoring.html.md.erb
[#178666913]
Authored-by: Colin Shield <cshield@vmware.com>
> first pass at a monitoring page

- connecting-apps.html.md.erb
- connecting-tas.html.md.erb
@colins and I tried this and it eventually worked.
Thanks folks!
> Add manual instructions to connect a TAS app to this mysql K8s instance

- upgrade-instance.html.md.erb
Name the branches to merge this change with or enter "None": `main`
The page is available for review at https://mysql-upgrade-instance.sc2-04-pcf1-apps.oc.vmware.com/tanzu-mysql-kubernetes/1-n/upgrade-instance.html
> First draft of 'Upgrading MySQL Instances'

- connecting-tas.html.md.erb
Name the branches to merge this change with or enter "None": `main`
Revisions to the topic added in #55.
The changes can be viewed at https://mysql-k8s-connecting-tas.sc2-04-pcf1-apps.oc.vmware.com/tanzu-mysql-kubernetes/1-1/connecting-tas.html
> Edit topic about connecting a TAS app

- configure-tls.html.md.erb
Name the branches to merge this change with or enter "None". 1.1 and 1.0 branches can accept this fix as well.
> Fix typo in ssl-mode value

- release-notes.html.md.erb
Name the branches to merge this change with or enter "None". 1.1 branch
> Fix typo in link to Percona release notes

- README.md
- create-delete-mysql.html.md.erb
- install-operator.html.md.erb
- upgrade-operator.html.md.erb
Co-authored-by: Kim Bassett <kbassett@vmware.com>
None. (We expect this to take effect in later release 1.3.0)
> Replace "registry.pivotal.io" with "registry.tanzu.vmware.com"

- high-availability.html.md.erb
- toc.md
- troubleshooting.html.md.erb
Name the branches to merge this change with or enter "None": None
https://www.pivotaltracker.com/story/show/180893361
> Document HA schema compatibility requirements and troubleshooting

- connecting-apps.html.md.erb
[#181238621]https://www.pivotaltracker.com/story/show/181238621
Authored-by: Kyle Ong <kyleo@vmware.com>
> connecting-apps: Fix copy and paste code blocks

- create-delete-mysql.html.md.erb
- high-availability.html.md.erb
- property-reference-mysql.html.md.erb
(Merge with Main)
Mostly changes relating to spec.storageSize becoming Optional instead of no longer Required.
While making those changes, I corrected two other errors: imagePullSecret's property description (= no longer Required, this is Optional) and yaml indentation+structure around affinity+tolerations.
> V1 3 0 storage size

- install-operator.html.md.erb
- network-policies.html.md.erb
> Network Policy Configuration: Add docs for network policies

- README.md
- install-operator.html.md.erb
- upgrade-operator.html.md.erb
[#181304669]
Authored-by: Kyle Ong <kyleo@vmware.com>
> install-operator: Prepend a $ to env-vars

- property-reference-mysql.html.md.erb
- Update yaml property values to match updates in our shipped yaml samples
- Align yaml examples to be 2-space indented
> Tanzu mysql k8s property updates

- install-operator.html.md.erb
- upgrade-operator.html.md.erb
[#181672344]
Authored-by: Kyle Ong <kyleo@vmware.com>
> install / upgrade-operator: Use mktemp -d to export chart

- install-operator.html.md.erb
[#181129167](https://www.pivotaltracker.com/story/show/181129167)
Co-authored-by: Yiming Li <yimingli@vmware.com>
> install-operator: Update for multi-version installation

- create-delete-mysql.html.md.erb
- install-operator.html.md.erb
- release-notes.html.md.erb
> 1.4.0 multi version clarifications

- backup-restore.html.md.erb
- property-reference-backup-restore.html.md.erb
- release-notes.html.md.erb
[#174154868](https://www.pivotaltracker.com/story/show/174154868)
Co-authored-by: Shelby Miller <mshelby@vmware.com>
> Update docs to include caBundle field

- install-operator.html.md.erb
- upgrade-operator.html.md.erb
Name the branches to merge this change with or enter "None". 1.6
> upgrade-operator: Improve helm instructions and add tanzu upgrade

- migrate-mysql.html.md.erb
- toc.md
[#183906107](https://www.pivotaltracker.com/story/show/183906107)
> Add documentation for migrating from TAS to k8s

- backup-restore.html.md.erb
- create-delete-mysql.html.md.erb
- index.html.md.erb
- install-operator.html.md.erb
- release-notes.html.md.erb
- update-instance.html.md.erb
- upgrade-operator.html.md.erb
[#184017291](https://www.pivotaltracker.com/story/show/184017291)
> Add release notes for 1.6.2

- architecture.html.md.erb
- backup-restore.html.md.erb
- property-reference-backup-restore.html.md.erb
[#184005022](https://www.pivotaltracker.com/story/show/184005022)
Co-authored-by: Shelby Miller <mshelby@vmware.com>
> Add documentation for Azure support for backups [1.7.0]

- create-delete-mysql.html.md.erb
- install-operator.html.md.erb
[#184009650](https://www.pivotaltracker.com/story/show/184009650)
Authored-by: Swati Nair <nswati@vmware.com>
[Merge it in main]
> [1.7.0] Add Openshift support docs

- release-notes.html.md.erb
[#184261881](https://www.pivotaltracker.com/story/show/184261881)
> Add 1.7.0 to release notes

- install-operator.html.md.erb
- quick-start-script.bash
- release-notes.html.md.erb
[#184586760](https://www.pivotaltracker.com/story/show/184586760)
> [1.7.0] Remove charts/ prefix from helm OCI artifact reference

- index.html.md.erb
- release-notes.html.md.erb
> [1.7.0] Update 1.7.0 release date

- backup-restore.html.md.erb
- create-delete-mysql.html.md.erb
- index.html.md.erb
- install-operator.html.md.erb
- release-notes.html.md.erb
- upgrade-operator.html.md.erb
> Add 1.7.1 release notes

- release-notes.html.md.erb
[#185193164](https://www.pivotaltracker.com/story/show/185193164)
Name the branches to merge this change with or enter "None". 1.7 branch and newer
> Simplify documentation around supported platforms

- architecture.html.md.erb
- backup-restore.html.md.erb
- update-instance.html.md.erb
Name the branches to merge this change with or enter "None". 1.7 branch and main
> Update docs for CRD overview

- 1
- architecture.html.md.erb
- backup-restore.html.md.erb
- create-delete-mysql.html.md.erb
- index.html.md.erb
- install-operator.html.md.erb
- property-reference-mysql.html.md.erb
- quick-start.html.md.erb
- release-notes.html.md.erb
- rotating-credentials.html.md.erb
- update-instance.html.md.erb
- upgrade-instance.html.md.erb
- upgrade-operator.html.md.erb
[#184760927](https://www.pivotaltracker.com/story/show/184760927)
> Update docs for 1.8.0 and new MySQL version

- accessing.html.md.erb
- connecting-apps.html.md.erb
- release-notes.html.md.erb
[#185063152](https://www.pivotaltracker.com/story/show/185063152)
> Document mysql-admin user

- install-operator.html.md.erb
- upgrade-operator.html.md.erb
[#185091344](https://www.pivotaltracker.com/story/show/185091344)
Name the branches to merge this change with or enter "None". 1.8
> [1.8.0] Update package installation docs for readability

- property-reference-mysql.html.md.erb
Name the branches to merge this change with or enter "None". 1.8
> [1.8+] Describe behavior when MySQL memory limit is too low

- property-reference-mysql.html.md.erb
Name the branches to merge this change with or enter "None". 1.8 and main
> [1.8+] Fix indentation in CRD resources section

- configure-mysql-server.html.md.erb
- property-reference-mysql.html.md.erb
- release-notes.html.md.erb
Name the branches to merge this change with or enter "None". Just the `main` branch since this is a 1.9 feature.
> Describe how to customize server configuration

- release-notes.html.md.erb
If possible, we should backport to the 1.7 branch as well.
> Add known issue for bucket path

- release-notes.html.md.erb
- upgrade-operator.html.md.erb
Two notes for upgrade best practice
> 1.9.0 -  Upgrade the operator from 1.8.0

- property-reference-backup-restore.html.md.erb
- release-notes.html.md.erb
[TSQL-265](https://jira.eng.vmware.com/browse/TSQL-265)
> [1.9] Document new Azure storage field for CA bundle

- release-notes.html.md.erb
[TSQL-276](https://jira.eng.vmware.com/browse/TSQL-276)
Name the branches to merge this change with or enter "None". `1.8`
> [1.8] Add limitation for using MySQL as chart dependency

- backup-restore.html.md.erb
- property-reference-backup-restore.html.md.erb
- release-notes.html.md.erb
> [1.9] Document binary logs and point-in-time recovery

- backup-restore.html.md.erb
- create-delete-mysql.html.md.erb
- install-operator.html.md.erb
- quick-start.html.md.erb
- rotating-credentials.html.md.erb
- upgrade-operator.html.md.erb
> Replace 1.8.0 with 1.9.0

- release-notes.html.md.erb
limititations, and upgrade
Co-authored-by: Ria Mahoney <mpatrice@vmware.com>
> Final changes to release notes, known issues,

- install-operator.html.md.erb
- upgrade-operator.html.md.erb
v1.0.0 of the Tanzu CLI has significant changes from prior versions. Update our instructions to reflect them.
main, 1.9
> Update install and upgrade instruction using Tanzu CLI

- index.html.md.erb
Fixing broken link in the https://docs.vmware.com/en/VMware-SQL-with-MySQL-for-Kubernetes/1.5/vmware-mysql-k8s/index.html topic per https://bugzilla.eng.vmware.com/show_bug.cgi?id=3294759.
> Fixing a link per bug 3294759

- index.html.md.erb
Branch 1.6.
Fixing links per bug https://bugzilla.eng.vmware.com/show_bug.cgi?id=3294770#c2 in https://docs.vmware.com/en/VMware-SQL-with-MySQL-for-Kubernetes/1.6/vmware-mysql-k8s/index.html
> Fixing links per bug 3294770

- index.html.md.erb
Branch 1.9 from updates-for-1.9-bug-pr3294772.
Fixing links per bug https://bugzilla.eng.vmware.com/show_bug.cgi?id=3294772 in https://docs.vmware.com/en/VMware-SQL-with-MySQL-for-Kubernetes/1.9/vmware-mysql-k8s/index.html.
> Fixing links per bug 3294772 (#156)

- creating-service-bindings.html.md.erb
- migrate-mysql.html.md.erb
> Fixing broken links per bug_3297245_3297237

- creating-service-bindings.html.md.erb
- migrate-mysql.html.md.erb
> Fixing broken links per bugs_3297245_3297237. (#159)

- index.html.md.erb
- release-notes.html.md.erb
> Updates for 1.10.1 release.

- creating-service-bindings.html.md.erb
- index.html.md.erb
- migrate-mysql.html.md.erb
- release-notes.html.md.erb
- toc.md
Merge changes from the updates-for-1.10.1 branch to branch 1.10.
> Merge changes from the updates-for-1.10.1 branch to branch 1.10.
